script: "echo nothing to do"
before_deploy:
  - export BINARY=$(python update_version.py)
  - echo OK $BINARY

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $BINARY
  skip_cleanup: true
  on:
    tags: true