script:
  - export BINARY=$(python update_version.py)
  - python -c "import zipfile,os;print(zipfile.ZipFile(os.environ['BINARY']).namelist())"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $BINARY
  skip_cleanup: true
  on:
    tags: true